from .pycolab_env import PyColabEnv
from .mazeworld_env import Maze
from .mazeworld_env import FiveRoom
from .mazeworld_env import FiveRoomWhitenoise
from .mazeworld_env import FiveRoomFlipped
from .mazeworld_env import FiveRoomAll
from .mazeworld_env import FiveRoomLong
from .mazeworld_env import FiveRoomLongwide
from .mazeworld_env import FiveRoomLongunpadded
from .mazeworld_env import FiveRoomLongExt
from .mazeworld_env import FiveRoomNoobj
from .mazeworld_env import FiveRoomOneobj
from .mazeworld_env import FiveRoomOnewhite
from .mazeworld_env import FiveRoomRandomfixed
from .mazeworld_env import FiveRoomBouncing
from .mazeworld_env import FiveRoomBrownian
from .mazeworld_env import FiveRoomMoveable
from .mazeworld_env import FiveRoomMoveableStoch
from .mazeworld_env import FiveRoomExtInt
from .mazeworld_env import FiveRoomMoveableBrownian
from .mazeworld_env import FiveRoomXL
from .mazeworld_env import FiveRoomXLExtInt
from .mazeworld_env import FiveRoomXLWhitenoise
from .mazeworld_env import FiveRoomXLWeather
from .mazeworld_env import FiveRoomXLEnemy1
from .mazeworld_env import FiveRoomXLEnemy2
from .mazeworld_env import FiveRoomXLText
from .mazeworld_env import FiveRoomXLTextWhitenoise
from .mazeworld_env import FiveRoomXLRandomfixed
from .mazeworld_env import FiveRoomXLTextRandomfixed
from .mazeworld_env import FiveRoomXLMoveable
from .mazeworld_env import FiveRoomXLMoveableExt
from .mazeworld_env import FiveRoomXLTextMoveable
from .mazeworld_env import FiveRoomXLMoveableStoch
from .mazeworld_env import FiveRoomXLMoveableStochExt
from .mazeworld_env import FiveRoomXLTextMoveableStoch
from .mazeworld_env import FiveRoomXLMoveableBrownian
from .mazeworld_env import FiveRoomXLTextMoveableBrownian
from .mazeworld_env import FiveRoomXLBrownian
from .mazeworld_env import FiveRoomXLTextBrownian
from .mazeworld_env import FiveRoomXLAll
from .mazeworld_env import FiveRoomXLAllExt
from .mazeworld_env import FiveRoomXLAllStoch
from .mazeworld_env import FiveRoomXLAllStochExt
from .mazeworld_env import FiveRoomXLTextAll
from .mazeworld_env import EightRoom
from .mazeworld_env import EightRoomDiff
from .mazeworld_env import EightRoomDiffRotated
from .mazeworld_env import EightRoomDiffWhite
from .mazeworld_env import EightRoomExt
from .mazeworld_env import EightRoomRgb
from .mazeworld_env import EightRoomWeather
from .mazeworld_env import EightRoomXLExt
from .mazeworld_env import EightRoomXLWeather
from .mazeworld_env import EightRoomHardExt
from .mazeworld_env import EightRoomHardWeather
from .mazeworld_env import PianoLong
from .mazeworld_env import Aligned
from .mazeworld_env import Misaligned